# Generated by Django 2.1.15 on 2020-03-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManualProductIds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30)),
                ('capsula', models.CharField(max_length=30)),
                ('productid', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=30)),
                ('multiplicador_dose', models.DecimalField(decimal_places=2, max_digits=5)),
                ('multiplicador_capsula', models.DecimalField(decimal_places=2, max_digits=5)),
                ('multiplicador_caixa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('child_productid', models.CharField(max_length=50)),
                ('sku_ga', models.CharField(max_length=50)),
                ('produto_ga', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'manual_productids',
                'managed': False,
            },
        ),
    ]
