# Generated by Django 3.0.3 on 2020-02-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_crawler_inissia_daily', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricecrawlerinissia',
            old_name='data_de_extração',
            new_name='data_de_extracao',
        ),
        migrations.RenameField(
            model_name='pricecrawlerinissia',
            old_name='preço',
            new_name='preco',
        ),
    ]
