# Generated by Django 3.0.3 on 2020-02-23 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_crawler_inissia_daily', '0002_auto_20200223_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricecrawlerinissia',
            options={'managed': False},
        ),
    ]
