# Generated by Django 2.1.15 on 2020-03-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_crawler', '0003_pricecrawlerevolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCrawlerPrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja', models.CharField(max_length=50)),
                ('produto', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'machine_print',
                'managed': False,
            },
        ),
    ]
