# Generated by Django 2.1.15 on 2020-03-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_crawler', '0004_pricecrawlerprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCrawler_old',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50)),
                ('data_de_extracao', models.DateField()),
                ('loja', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'db_table': 'price_crawler_hist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PriceCrawlerEvolution_old',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_extracao', models.DateField()),
                ('mini_me', models.DecimalField(decimal_places=2, max_digits=7)),
                ('essenza', models.DecimalField(decimal_places=2, max_digits=7)),
                ('inissia', models.DecimalField(decimal_places=2, max_digits=7)),
                ('mimo_cafeteira', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pop_plus', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'db_table': 'price_crawler_evolution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PriceCrawlerMin_old',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50)),
                ('data_de_extracao', models.DateField()),
                ('loja', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'db_table': 'price_crawler_min',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PriceCrawlerPrint_old',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja', models.CharField(max_length=50)),
                ('produto', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'machine_print',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='pricecrawler',
            table='price_crawler_hist',
        ),
        migrations.AlterModelTable(
            name='pricecrawlerevolution',
            table='price_crawler_evolution',
        ),
        migrations.AlterModelTable(
            name='pricecrawlermin',
            table='price_crawler_min',
        ),
    ]
